extends SceneTree
const Paths = preload("res://Workshop/Rooms/UI Foundation/Prototype/domain/movement_preview.gd")
const Items = preload("res://Workshop/Rooms/UI Foundation/Prototype/gameplay/items.gd")
var checks: int = 0
func check(value: bool, message: String) -> void:
	checks += 1
	if not value:
		push_error("Prototype/tests/map_world_test.gd: "+message)
		quit(1)
		assert(value,message)
func _initialize() -> void: call_deferred("run")
func run() -> void:
	var game = load("res://Workshop/Rooms/UI Foundation/Prototype/ui/main.tscn").instantiate()
	root.add_child(game)
	game.dice_slots = [0,0,0,0,0,0,4,4,4,4,4,4]
	game._start_run()
	check(game.active_map.layer == "Global" and not game.battle,"global start")
	check(game.active_map.links.size() == 432,"every global hex links to local")
	game._enter_map()
	check(game.active_map.layer == "Local","enter region")
	var local_id: String = game.active_map.id
	check(game.active_map.links.size() == 4,"local exit and three POIs")
	game._request_movement(Vector2i(4,2),true)
	check(game.player.pos == Vector2i(4,2),"walk to dungeon")
	game._enter_map()
	check(game.battle and game.active_map.dimensions == Vector2i(18,14),"dungeon encounter and extent")
	var dungeon_id: String = game.active_map.id
	check(not game._movement_paths().has(Vector2i(4,3)),"wall excluded")
	check(game.active_map.walkable(Vector2i(7,3)),"grid beyond old seven columns")
	var paths: Dictionary = Paths.paths(Vector2i(3,3),8,[],game.active_map)
	check(paths.has(Vector2i(5,3)),"route around wall")
	for cell: Vector2i in paths[Vector2i(5,3)]: check(game.active_map.walkable(cell),"path walkable")
	game.player.skills.append("Lunge")
	game.mode = "lunge"
	game._refresh()
	check(Vector2i(2,4) in game.board.highlights,"lunge can turn")
	game._board_intent(Vector2i(2,4),false)
	check(game.player.pos == Vector2i(2,4) and game.actions.attack == 0 and game.actions.move == 1,"lunge uses attack only")
	game._command("Cancel")
	game.player.pos = Vector2i(1,3)
	game.enemy.hp = 5
	game.loot.append({"item":Items.potion(),"pos":Vector2i(2,3)})
	var item_id: int = game.loot[0].item.item_id
	game._enter_map()
	check(game.active_map.id == local_id,"dungeon exit")
	check(game.player.pos == Vector2i(4,2) and not game.battle,"local position restored")
	game._enter_map()
	check(game.active_map.id == dungeon_id and game.enemy.hp == 5,"enemy state persists")
	check(game.loot.size() == 1 and game.loot[0].item.item_id == item_id,"loot persists")
	check(game.actions.activation == 0 and game.actions.attack == 0,"travel does not reset actions")
	game._enter_map()
	check(game.active_map.id == dungeon_id,"no free combat exit")
	game.player.hp = 999
	game._end_turn()
	check(game.active_map.walkable(game.enemy.pos),"enemy avoids walls")
	game.enemy.hp = 0
	game._check_death()
	var count: int = game.loot.size()
	game._enter_map()
	game._enter_map()
	check(not game.battle and game.enemy.hp == 0 and game.loot.size() == count,"dead enemy and loot retained without duplication")
	game._enter_map()
	game._request_movement(Vector2i(1,3),true)
	game._enter_map()
	check(game.active_map.layer == "Global" and game.player.pos == Vector2i(2,2),"full return trip")
	game.player.pos = Vector2i(0,0)
	game._enter_map()
	check(game.active_map.id != local_id,"different world hex gets different local map")
	game.player.pos = Vector2i(3,4)
	game._enter_map()
	check(game.active_map.title == "Town" and not game.battle,"town uses same grid without combat")
	game._enter_map()
	game.player.pos = Vector2i(5,4)
	game._enter_map()
	check(game.active_map.title == "Tower" and game.battle,"tower child encounter")
	game._start_run()
	check(game.map_world.states.is_empty(),"new run clears maps")
	print("Prototype/tests/map_world_test.gd: %d checks passed" % checks)
	quit()
